project:
  type: website
  output-dir: docs

website:
  title: "My Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: leetcode.qmd
        text: LeetCode Hot 100

format:
  html:
    theme: cosmo
    toc: true