project:
  type: website
  output-dir: docs

website:
  title: "My Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: leetcode.qmd
        text: LeetCode HOT 100
      - href: sqlpandas.qmd
        text: SQL & pandas

format:
  html:
    theme: cosmo
    toc: true